# Significance Testing {#signif}

The main reason I HATE statistics is because I hate the procedure called "null hypothesis significance testing" (NHST). In many areas of psychology, and most statistics textbooks for psychology students, "statistics" and NHST are one and the same. Hence "I hate **"statistics"**. 

Sometime between 1900 and 1908, the word "significant" and the concept of "significance testing" seem to have come in common use among statisticians. I say this because in the two very influential papers published in those years, Pearson [-@pearson1900] never mentions it, while Gossett (Student) [-@student1908], just 8 years later, uses "significance" early in his paper with no introduction or definition.

TheN, as discussed in the previous chapter, Sir Ronald Fisher published a textbook that brought statistics to the masses [@fisher]. It summarized and gave examples of an easy to follow recipe for analyzing data, which goes something like this:

* All data are to be compared to a "null hypothesis", which is something like
    - my groups of data are all really the same, or
    - my two variables are unrelated 
* Compute a numerical score using the relatively simple formulae provided
* Compare your score to a table of scores corresponding to various probabilities under the null hypothesis
* if the chances of your score (or one more extreme) are lower than 1 in 20, then declare your results "significant" and consider the null hypothesis refuted!

Simple, right! And so straightforward! Now if I'm some mid-level government official in the health department tasked with seeing if malaria cases have increased this year over last, I need to fret about what is a "real" increase vs. normal year to year variability. I need not concern myself with wasting a sheet of graph paper plotting the data, etc. I just have to follow the recipe, and it will **decisively** if there has been a ***significant*** increase in malaria this year!

The only trouble with this is... ***IT'S STUPID!*** 

This is nothing against Fisher. There is no way that he could have possibly imagined the stupidity unleashed by what was meant to be a simple practical field guide to analyzing data.
